apiVersion: v1
kind: Pod
metadata:
  name: bad-image
  namespace: week3
  labels:
    app: bad-image
spec:
  containers:
    - name: nginx
      image: nginx:not-a-real-tag
      ports:
        - containerPort: 80

