apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo
  namespace: week3
  labels:
    app: api-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-demo
  template:
    metadata:
      labels:
        app: api-demo
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80

